# GENERAL
iterations: 400000
max_code_length: 32
reset_for_every_run: False
num_vms_per_env: 100
action_masking: False

# REWARDs
only_reward_on_ret: True
punish_cap: 24

# ENVIRONMENT -- GRAPH Generation
min_n: 3
min_m: 3
max_n: 3
max_m: 3

# MODEL
policy_net: [1024, 1024, 1024, 1024, 1024]
