# GENERAL
iterations: 250000
max_code_length: 64
reset_for_every_run: False
num_vms_per_env: 100
action_masking: True
vectorize_environment: False

# REWARDs
only_reward_on_ret: True
punish_cap: 48

# ENVIRONMENT -- GRAPH Generation
min_n: 4
min_m: 6
max_n: 4
max_m: 6


# MODEL
gamma: 0.99
layer_dim_pi: 256
layer_dim_vf: 256
feature_dim: 256

fe_d_model: 128
fe_nhead: 4
fe_num_blocks: 4

reward_fn:
  punish_code_length: 1.0
  f_score_mst: 1.0

  reward_finite_runtime: 0.0 # bad values (skew the reward)
  reward_valid_spanning_tree_length: 0.0
  reward_no_cycles: 0.0 # not implemented
  reward_covered_nodes: 0.0
  reward_minimality: 0.0 # bad values (skew the reward)
  reward_efficiency: 0.0
  reward_distance_to_MST: 0.0
  reward_correct_edges: 0.0
  reward_connected: 0.0
  punish_mst_weight_too_large: 0.0
